/*
 * Auto-generated lexer mappings implementation
 * Generated by tools/generate_lexer_code.py
 * DO NOT EDIT - This file is automatically generated
 */

#include "lexer_mappings_generated.h"

/* ada primary keywords */
static const char* g_AdaKeywords =
    "abort abs abstract accept access aliased all and array at begin body case constant declare delay delta digits do else elsif end entry exception exit for function generic goto if in interface is limited loop mod new not null of or others out overriding package pragma private procedure protected raise range record rem renames requeue return reverse select separate some subtype synchronized tagged task terminate then type until use when while with xor";

/* bash primary keywords */
static const char* g_BashKeywords =
    "if then else elif fi case esac for while until do done in function select time coproc";

/* clojure primary keywords */
static const char* g_ClojureKeywords =
    "def defmacro defn defstruct deftype defprotocol defrecord ns import use require if do let loop recur when when-not when-let when-first for doseq dotimes and or not";

/* cpp primary keywords */
static const char* g_CppKeywords =
    "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq";

/* cpp secondary keywords */
static const char* g_CppKeywords2 =
    "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator";

/* css primary keywords */
static const char* g_CssKeywords =
    "color background font margin padding border width height display position top left right bottom float clear text-align vertical-align line-height font-size font-family font-weight overflow visibility z-index opacity transform transition animation flex grid justify-content align-items";

/* erlang primary keywords */
static const char* g_ErlangKeywords =
    "after and andalso band begin bnot bor bsl bsr bxor case catch cond div end fun if let not of or orelse query receive rem try when xor";

/* fortran primary keywords */
static const char* g_FortranKeywords =
    "program module subroutine function end use implicit none integer real character logical dimension parameter common equivalence data save allocate deallocate";

/* haskell primary keywords */
static const char* g_HaskellKeywords =
    "case class data default deriving do else if import in infix infixl infixr instance let module newtype of then type where";

/* julia primary keywords */
static const char* g_JuliaKeywords =
    "abstract break case catch const continue do else elseif end export finally for function global if import let local macro module quote return struct try type using while";

/* lua primary keywords */
static const char* g_LuaKeywords =
    "and break do else elseif end false for function goto if in local nil not or repeat return then true until while";

/* matlab primary keywords */
static const char* g_MatlabKeywords =
    "break case catch classdef continue else elseif end for function global if otherwise parfor persistent return spmd switch try while";

/* pascal primary keywords */
static const char* g_PascalKeywords =
    "and array as begin case class const constructor destructor div do downto else end except finally for function goto if implementation in inherited interface is mod not object of on or packed procedure program property raise record repeat set shl shr then to try type unit until uses var while with xor";

/* perl primary keywords */
static const char* g_PerlKeywords =
    "if else elsif unless while until for foreach do last next redo goto return sub package use require BEGIN END my local our";

/* powershell primary keywords */
static const char* g_PowershellKeywords =
    "begin break catch class continue data define do dynamicparam else elseif end exit filter finally for foreach from function if in inlineScript parallel param process return switch throw trap try until where while workflow";

/* python primary keywords */
static const char* g_PythonKeywords =
    "and as assert async await break class continue def del elif else except finally for from global if import in is lambda None not or pass raise return try while with yield True False";

/* r primary keywords */
static const char* g_RKeywords =
    "if else repeat while function for in next break TRUE FALSE NULL NA Inf NaN";

/* registry primary keywords */
static const char* g_RegistryKeywords =
    "HKEY_CLASSES_ROOT HKEY_CURRENT_USER HKEY_LOCAL_MACHINE HKEY_USERS HKEY_CURRENT_CONFIG REG_SZ REG_DWORD REG_BINARY REG_MULTI_SZ REG_EXPAND_SZ REG_NONE REG_QWORD REG_DWORD_BIG_ENDIAN REG_LINK REG_RESOURCE_LIST REG_FULL_RESOURCE_DESCRIPTOR REG_RESOURCE_REQUIREMENTS_LIST REG_QWORD_LITTLE_ENDIAN DELETE READ_CONTROL WRITE_DAC WRITE_OWNER";

/* ruby primary keywords */
static const char* g_RubyKeywords =
    "BEGIN END alias and begin break case class def defined? do else elsif end ensure false for if in module next nil not or redo rescue retry return self super then true undef unless until when while yield";

/* rust primary keywords */
static const char* g_RustKeywords =
    "as break const continue crate dyn else enum extern false fn for if impl in let loop match mod move mut pub ref return self Self static struct super trait true type unsafe use where while";

/* sql primary keywords */
static const char* g_SqlKeywords =
    "select from where and or not in is null as order by group having join left right inner outer on union all distinct count sum avg min max";

/* verilog primary keywords */
static const char* g_VerilogKeywords =
    "always and assign automatic begin buf bufif0 bufif1 case casex casez cell cmos config deassign default defparam design disable edge else end endcase endconfig endfunction endgenerate endmodule endprimitive endspecify endtable endtask event for force forever fork function generate genvar highz0 highz1 if ifnone incdir include initial inout input instance join large liblist library localparam macromodule medium module nand negedge nmos nor noshowcancelled not notif0 notif1 or output parameter pmos posedge primitive pull0 pull1 pulldown pullup pulsestyle_ondetect pulsestyle_onevent rcmos real realtime reg release repeat rnmos rpmos rtran rtranif0 rtranif1 scalared showcancelled signed small specify specparam strong0 strong1 supply0 supply1 supply1 table task time tran tranif0 tranif1 tri tri0 tri1 triand trior trireg use uwire vectored wait wand weak0 weak1 while wire wor xnor xor";

/* vhdl primary keywords */
static const char* g_VhdlKeywords =
    "abs access after alias all and architecture array assert attribute begin block body buffer bus case component configuration constant disconnect downto else elsif end entity exit file for function generate generic group guarded if impure in inertial inout is label library linkage literal loop map mod nand new next nor not null of on open or others out package port postponed procedure process pure range record register reject rem report return rol ror select severity signal shared sla sll sra srl subtype then to transport type unaffected units until use variable wait when while with xnor xor";

/* Extension to LanguageType mapping - generated from GitHub Linguist */
const ExtensionMapping g_extensionMappings[] = {
    {".4dform", LANG_JSON},
    {".4dproject", LANG_JSON},
    {"._coffee", LANG_COFFEESCRIPT},
    {"._js", LANG_JAVASCRIPT},
    {".a51", LANG_ASSEMBLY},
    {".ada", LANG_ADA},
    {".adb", LANG_ADA},
    {".adml", LANG_XML},
    {".admx", LANG_XML},
    {".adp", LANG_TCL},
    {".ads", LANG_ADA},
    {".al", LANG_PERL},
    {".ant", LANG_XML},
    {".app", LANG_ERLANG},
    {".app.src", LANG_ERLANG},
    {".asm", LANG_ASSEMBLY},
    {".aux", LANG_TEX},
    {".avsc", LANG_JSON},
    {".axaml", LANG_XML},
    {".axml", LANG_XML},
    {".bash", LANG_SHELL},
    {".bat", LANG_BATCHFILE},
    {".bats", LANG_SHELL},
    {".bb", LANG_CLOJURE},
    {".bbx", LANG_TEX},
    {".bones", LANG_JAVASCRIPT},
    {".boot", LANG_CLOJURE},
    {".builder", LANG_RUBY},
    {".builds", LANG_XML},
    {".c", LANG_C},
    {".c++", LANG_CPP},
    {".cake", LANG_COFFEESCRIPT},
    {".cats", LANG_C},
    {".cbl", LANG_COBOL},
    {".cbx", LANG_TEX},
    {".cc", LANG_CPP},
    {".ccp", LANG_COBOL},
    {".ccproj", LANG_XML},
    {".ccxml", LANG_XML},
    {".cfg", LANG_INI},
    {".cgi", LANG_SHELL},
    {".cjs", LANG_JAVASCRIPT},
    {".cjsx", LANG_COFFEESCRIPT},
    {".cl2", LANG_CLOJURE},
    {".clixml", LANG_XML},
    {".clj", LANG_CLOJURE},
    {".cljc", LANG_CLOJURE},
    {".cljs", LANG_CLOJURE},
    {".cljs.hl", LANG_CLOJURE},
    {".cljscm", LANG_CLOJURE},
    {".cljx", LANG_CLOJURE},
    {".cls", LANG_TEX},
    {".cmake", LANG_CMAKE},
    {".cmake.in", LANG_CMAKE},
    {".cmd", LANG_BATCHFILE},
    {".cnf", LANG_INI},
    {".cob", LANG_COBOL},
    {".cobol", LANG_COBOL},
    {".coffee", LANG_COFFEESCRIPT},
    {".command", LANG_SHELL},
    {".containerfile", LANG_DOCKERFILE},
    {".cp", LANG_CPP},
    {".cpp", LANG_CPP},
    {".cppm", LANG_CPP},
    {".cproject", LANG_XML},
    {".cpy", LANG_COBOL},
    {".cs", LANG_CS},
    {".cs.pp", LANG_CS},
    {".cscfg", LANG_XML},
    {".csdef", LANG_XML},
    {".csl", LANG_XML},
    {".csproj", LANG_XML},
    {".css", LANG_CSS},
    {".csv", LANG_CSV},
    {".csx", LANG_CS},
    {".ct", LANG_XML},
    {".cts", LANG_TYPESCRIPT},
    {".cxx", LANG_CPP},
    {".d", LANG_MAKEFILE},
    {".dart", LANG_DART},
    {".ddl", LANG_SQL},
    {".depproj", LANG_XML},
    {".dfm", LANG_PASCAL},
    {".di", LANG_D},
    {".diff", LANG_DIFF},
    {".dita", LANG_XML},
    {".ditamap", LANG_XML},
    {".ditaval", LANG_XML},
    {".dll.config", LANG_XML},
    {".dockerfile", LANG_DOCKERFILE},
    {".dof", LANG_INI},
    {".dotsettings", LANG_XML},
    {".dpr", LANG_PASCAL},
    {".dtx", LANG_TEX},
    {".eliom", LANG_OCAML},
    {".eliomi", LANG_OCAML},
    {".erl", LANG_ERLANG},
    {".es", LANG_JAVASCRIPT},
    {".es6", LANG_JAVASCRIPT},
    {".escript", LANG_ERLANG},
    {".ex", LANG_ELIXIR},
    {".exs", LANG_ELIXIR},
    {".eye", LANG_RUBY},
    {".f", LANG_FORTRAN},
    {".f77", LANG_FORTRAN},
    {".fcgi", LANG_SHELL},
    {".filters", LANG_XML},
    {".for", LANG_FORTRAN},
    {".fpp", LANG_FORTRAN},
    {".frag", LANG_JAVASCRIPT},
    {".frm", LANG_INI},
    {".fs", LANG_FS},
    {".fsi", LANG_FS},
    {".fsproj", LANG_XML},
    {".fsx", LANG_FS},
    {".fun", LANG_STANDARD_ML},
    {".fxml", LANG_XML},
    {".gemspec", LANG_RUBY},
    {".geojson", LANG_JSON},
    {".glade", LANG_XML},
    {".gltf", LANG_JSON},
    {".gml", LANG_XML},
    {".gmx", LANG_XML},
    {".go", LANG_GO},
    {".god", LANG_RUBY},
    {".gpx", LANG_XML},
    {".gql", LANG_GRAPHQL},
    {".graphql", LANG_GRAPHQL},
    {".graphqls", LANG_GRAPHQL},
    {".grxml", LANG_XML},
    {".gs", LANG_JAVASCRIPT},
    {".gst", LANG_XML},
    {".gyp", LANG_PYTHON},
    {".gypi", LANG_PYTHON},
    {".h", LANG_OBJECTIVE_C},
    {".h++", LANG_CPP},
    {".h.in", LANG_C},
    {".har", LANG_JSON},
    {".hh", LANG_CPP},
    {".hic", LANG_CLOJURE},
    {".hpp", LANG_CPP},
    {".hrl", LANG_ERLANG},
    {".hs", LANG_HASKELL},
    {".hs-boot", LANG_HASKELL},
    {".hsc", LANG_HASKELL},
    {".hta", LANG_HTML},
    {".htm", LANG_HTML},
    {".html", LANG_HTML},
    {".html.hl", LANG_HTML},
    {".http", LANG_HTTP},
    {".hxx", LANG_CPP},
    {".hzp", LANG_XML},
    {".i", LANG_ASSEMBLY},
    {".ice", LANG_JSON},
    {".iced", LANG_COFFEESCRIPT},
    {".idc", LANG_C},
    {".iml", LANG_XML},
    {".inc", LANG_SQL},
    {".ini", LANG_INI},
    {".inl", LANG_CPP},
    {".ino", LANG_CPP},
    {".ins", LANG_TEX},
    {".ipp", LANG_CPP},
    {".ivy", LANG_XML},
    {".ixx", LANG_CPP},
    {".jake", LANG_JAVASCRIPT},
    {".jav", LANG_JAVA},
    {".java", LANG_JAVA},
    {".javascript", LANG_JAVASCRIPT},
    {".jbuilder", LANG_RUBY},
    {".jelly", LANG_XML},
    {".jl", LANG_JULIA},
    {".js", LANG_JAVASCRIPT},
    {".jsb", LANG_JAVASCRIPT},
    {".jscad", LANG_JAVASCRIPT},
    {".jsfl", LANG_JAVASCRIPT},
    {".jsh", LANG_JAVA},
    {".jslib", LANG_JAVASCRIPT},
    {".jsm", LANG_JAVASCRIPT},
    {".json", LANG_JSON},
    {".json-tmlanguage", LANG_JSON},
    {".json.example", LANG_JSON},
    {".jsonl", LANG_JSON},
    {".jspre", LANG_JAVASCRIPT},
    {".jsproj", LANG_XML},
    {".jss", LANG_JAVASCRIPT},
    {".jsx", LANG_JAVASCRIPT},
    {".kml", LANG_XML},
    {".kojo", LANG_SCALA},
    {".ksh", LANG_SHELL},
    {".kt", LANG_KOTLIN},
    {".ktm", LANG_KOTLIN},
    {".kts", LANG_KOTLIN},
    {".launch", LANG_XML},
    {".lbx", LANG_TEX},
    {".lektorproject", LANG_INI},
    {".less", LANG_LESS},
    {".linq", LANG_CS},
    {".livemd", LANG_MARKDOWN},
    {".lmi", LANG_PYTHON},
    {".lpr", LANG_PASCAL},
    {".ltx", LANG_TEX},
    {".lua", LANG_LUA},
    {".m", LANG_OBJECTIVE_C},
    {".mak", LANG_MAKEFILE},
    {".make", LANG_MAKEFILE},
    {".makefile", LANG_MAKEFILE},
    {".markdown", LANG_MARKDOWN},
    {".matlab", LANG_MATLAB},
    {".mcmeta", LANG_JSON},
    {".md", LANG_MARKDOWN},
    {".mdown", LANG_MARKDOWN},
    {".mdpolicy", LANG_XML},
    {".mdwn", LANG_MARKDOWN},
    {".mir", LANG_YAML},
    {".mjml", LANG_XML},
    {".mjs", LANG_JAVASCRIPT},
    {".mk", LANG_MAKEFILE},
    {".mkd", LANG_MARKDOWN},
    {".mkdn", LANG_MARKDOWN},
    {".mkdown", LANG_MARKDOWN},
    {".mkfile", LANG_MAKEFILE},
    {".mkii", LANG_TEX},
    {".mkiv", LANG_TEX},
    {".mkvi", LANG_TEX},
    {".ml", LANG_STANDARD_ML},
    {".ml4", LANG_OCAML},
    {".mli", LANG_OCAML},
    {".mll", LANG_OCAML},
    {".mly", LANG_OCAML},
    {".mm", LANG_XML},
    {".mod", LANG_XML},
    {".mojo", LANG_XML},
    {".mspec", LANG_RUBY},
    {".mts", LANG_TYPESCRIPT},
    {".mxml", LANG_XML},
    {".mysql", LANG_SQL},
    {".nas", LANG_ASSEMBLY},
    {".nasm", LANG_ASSEMBLY},
    {".natvis", LANG_XML},
    {".ncl", LANG_XML},
    {".ndproj", LANG_XML},
    {".nim", LANG_NIM},
    {".nim.cfg", LANG_NIM},
    {".nimble", LANG_NIM},
    {".nimrod", LANG_NIM},
    {".nims", LANG_NIM},
    {".njs", LANG_JAVASCRIPT},
    {".nproj", LANG_XML},
    {".nse", LANG_LUA},
    {".nuspec", LANG_XML},
    {".odd", LANG_XML},
    {".osm", LANG_XML},
    {".p8", LANG_LUA},
    {".pac", LANG_JAVASCRIPT},
    {".pas", LANG_PASCAL},
    {".pascal", LANG_PASCAL},
    {".patch", LANG_DIFF},
    {".pd_lua", LANG_LUA},
    {".perl", LANG_PERL},
    {".ph", LANG_PERL},
    {".pkgproj", LANG_XML},
    {".pl", LANG_PERL},
    {".pluginspec", LANG_XML},
    {".plx", LANG_PERL},
    {".pm", LANG_PERL},
    {".podspec", LANG_RUBY},
    {".pp", LANG_PASCAL},
    {".prawn", LANG_RUBY},
    {".prc", LANG_SQL},
    {".prefs", LANG_INI},
    {".pro", LANG_INI},
    {".proj", LANG_XML},
    {".properties", LANG_INI},
    {".props", LANG_XML},
    {".ps1", LANG_POWERSHELL},
    {".ps1xml", LANG_XML},
    {".psc1", LANG_XML},
    {".psd1", LANG_POWERSHELL},
    {".psgi", LANG_PERL},
    {".psm1", LANG_POWERSHELL},
    {".pt", LANG_XML},
    {".pubxml", LANG_XML},
    {".py", LANG_PYTHON},
    {".py3", LANG_PYTHON},
    {".pyde", LANG_PYTHON},
    {".pyi", LANG_PYTHON},
    {".pyp", LANG_PYTHON},
    {".pyt", LANG_PYTHON},
    {".pyw", LANG_PYTHON},
    {".qhelp", LANG_XML},
    {".r", LANG_R},
    {".rabl", LANG_RUBY},
    {".rake", LANG_RUBY},
    {".rb", LANG_RUBY},
    {".rbi", LANG_RUBY},
    {".rbuild", LANG_RUBY},
    {".rbw", LANG_RUBY},
    {".rbx", LANG_RUBY},
    {".rbxs", LANG_LUA},
    {".rd", LANG_R},
    {".rdf", LANG_XML},
    {".re", LANG_CPP},
    {".reek", LANG_YAML},
    {".reg", LANG_WINDOWS_REGISTRY},
    {".res", LANG_XML},
    {".rest", LANG_RESTRUCTUREDTEXT},
    {".rest.txt", LANG_RESTRUCTUREDTEXT},
    {".resx", LANG_XML},
    {".rockspec", LANG_LUA},
    {".ronn", LANG_MARKDOWN},
    {".rpy", LANG_PYTHON},
    {".rs", LANG_XML},
    {".rs.in", LANG_RUST},
    {".rss", LANG_XML},
    {".rst", LANG_RESTRUCTUREDTEXT},
    {".rst.txt", LANG_RESTRUCTUREDTEXT},
    {".rsx", LANG_R},
    {".ru", LANG_RUBY},
    {".ruby", LANG_RUBY},
    {".rviz", LANG_YAML},
    {".s", LANG_ASSEMBLY},
    {".sarif", LANG_JSON},
    {".sass", LANG_SASS},
    {".sbatch", LANG_SHELL},
    {".sbt", LANG_SCALA},
    {".sc", LANG_SCALA},
    {".scala", LANG_SCALA},
    {".scd", LANG_MARKDOWN},
    {".sch", LANG_XML},
    {".scss", LANG_SCSS},
    {".scxml", LANG_XML},
    {".sdc", LANG_TCL},
    {".sfproj", LANG_XML},
    {".sh", LANG_SHELL},
    {".sh.in", LANG_SHELL},
    {".shproj", LANG_XML},
    {".sig", LANG_STANDARD_ML},
    {".sjs", LANG_JAVASCRIPT},
    {".slnx", LANG_XML},
    {".slurm", LANG_SHELL},
    {".sml", LANG_STANDARD_ML},
    {".spec", LANG_RUBY},
    {".sql", LANG_SQL},
    {".srdf", LANG_XML},
    {".ssjs", LANG_JAVASCRIPT},
    {".storyboard", LANG_XML},
    {".sty", LANG_TEX},
    {".sublime-snippet", LANG_XML},
    {".sublime-syntax", LANG_YAML},
    {".sw", LANG_XML},
    {".swift", LANG_SWIFT},
    {".syntax", LANG_YAML},
    {".t", LANG_PERL},
    {".tab", LANG_SQL},
    {".tac", LANG_PYTHON},
    {".tact", LANG_JSON},
    {".targets", LANG_XML},
    {".tcc", LANG_CPP},
    {".tcl", LANG_TCL},
    {".tcl.in", LANG_TCL},
    {".tex", LANG_TEX},
    {".tfstate", LANG_JSON},
    {".tfstate.backup", LANG_JSON},
    {".thor", LANG_RUBY},
    {".tm", LANG_TCL},
    {".tml", LANG_XML},
    {".tmux", LANG_SHELL},
    {".toc", LANG_TEX},
    {".toml", LANG_TOML},
    {".toml.example", LANG_TOML},
    {".tool", LANG_SHELL},
    {".topojson", LANG_JSON},
    {".tpp", LANG_CPP},
    {".trigger", LANG_SHELL},
    {".ts", LANG_TYPESCRIPT},
    {".tsv", LANG_TSV},
    {".tsx", LANG_TYPESCRIPT},
    {".txx", LANG_CPP},
    {".typ", LANG_XML},
    {".udf", LANG_SQL},
    {".ui", LANG_XML},
    {".urdf", LANG_XML},
    {".url", LANG_INI},
    {".ux", LANG_XML},
    {".v", LANG_VERILOG},
    {".vbproj", LANG_XML},
    {".vcf", LANG_TSV},
    {".vcxproj", LANG_XML},
    {".veo", LANG_VERILOG},
    {".vhd", LANG_VHDL},
    {".vhdl", LANG_VHDL},
    {".vhf", LANG_VHDL},
    {".vhi", LANG_VHDL},
    {".vho", LANG_VHDL},
    {".vhs", LANG_VHDL},
    {".vht", LANG_VHDL},
    {".vhw", LANG_VHDL},
    {".viw", LANG_SQL},
    {".vsixmanifest", LANG_XML},
    {".vssettings", LANG_XML},
    {".vstemplate", LANG_XML},
    {".vxml", LANG_XML},
    {".watchr", LANG_RUBY},
    {".webapp", LANG_JSON},
    {".webmanifest", LANG_JSON},
    {".wixproj", LANG_XML},
    {".wlua", LANG_LUA},
    {".workbook", LANG_MARKDOWN},
    {".workflow", LANG_XML},
    {".wsdl", LANG_XML},
    {".wsf", LANG_XML},
    {".wsgi", LANG_PYTHON},
    {".wxi", LANG_XML},
    {".wxl", LANG_XML},
    {".wxs", LANG_XML},
    {".x3d", LANG_XML},
    {".xacro", LANG_XML},
    {".xaml", LANG_XML},
    {".xdc", LANG_TCL},
    {".xht", LANG_HTML},
    {".xhtml", LANG_HTML},
    {".xib", LANG_XML},
    {".xlf", LANG_XML},
    {".xliff", LANG_XML},
    {".xmi", LANG_XML},
    {".xml", LANG_XML},
    {".xml.dist", LANG_XML},
    {".xmp", LANG_XML},
    {".xproj", LANG_XML},
    {".xpy", LANG_PYTHON},
    {".xrl", LANG_ERLANG},
    {".xsd", LANG_XML},
    {".xsjs", LANG_JAVASCRIPT},
    {".xsjslib", LANG_JAVASCRIPT},
    {".xspec", LANG_XML},
    {".xul", LANG_XML},
    {".yaml", LANG_YAML},
    {".yaml-tmlanguage", LANG_YAML},
    {".yaml.sed", LANG_YAML},
    {".yml", LANG_YAML},
    {".yml.mysql", LANG_YAML},
    {".yrl", LANG_ERLANG},
    {".yy", LANG_JSON},
    {".yyp", LANG_JSON},
    {".zcml", LANG_XML},
    {".zig", LANG_ZIG},
    {".zig.zon", LANG_ZIG},
    {".zsh", LANG_SHELL},
    {".zsh-theme", LANG_SHELL},
};

/* LanguageType to lexer configuration mapping */
const LexerConfig g_lexerConfigs[] = {
    {LANG_ADA, "ada", "abort abs abstract accept access aliased all and array at begin body case constant declare delay delta digits do else elsif end entry exception exit for function generic goto if in interface is limited loop mod new not null of or others out overriding package pragma private procedure protected raise range record rem renames requeue return reverse select separate some subtype synchronized tagged task terminate then type until use when while with xor", NULL},
    {LANG_ASSEMBLY, "asm", NULL, NULL},
    {LANG_BATCHFILE, "batch", NULL, NULL},
    {LANG_C, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_CS, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_CPP, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_CMAKE, "cmake", NULL, NULL},
    {LANG_COBOL, "cobol", NULL, NULL},
    {LANG_CSS, "css", "color background font margin padding border width height display position top left right bottom float clear text-align vertical-align line-height font-size font-family font-weight overflow visibility z-index opacity transform transition animation flex grid justify-content align-items", NULL},
    {LANG_CSV, "csv", NULL, NULL},
    {LANG_CLOJURE, "clojure", "def defmacro defn defstruct deftype defprotocol defrecord ns import use require if do let loop recur when when-not when-let when-first for doseq dotimes and or not", NULL},
    {LANG_COFFEESCRIPT, "coffeescript", NULL, NULL},
    {LANG_D, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_DART, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_DIFF, "diff", NULL, NULL},
    {LANG_DOCKERFILE, "dockerfile", NULL, NULL},
    {LANG_ELIXIR, "elixir", NULL, NULL},
    {LANG_ERLANG, "erlang", "after and andalso band begin bnot bor bsl bsr bxor case catch cond div end fun if let not of or orelse query receive rem try when xor", NULL},
    {LANG_FS, "fsharp", NULL, NULL},
    {LANG_FORTRAN, "fortran", "program module subroutine function end use implicit none integer real character logical dimension parameter common equivalence data save allocate deallocate", NULL},
    {LANG_GO, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_GRAPHQL, "graphql", NULL, NULL},
    {LANG_HTML, "hypertext", NULL, NULL},
    {LANG_HTTP, "http", NULL, NULL},
    {LANG_HASKELL, "haskell", "case class data default deriving do else if import in infix infixl infixr instance let module newtype of then type where", NULL},
    {LANG_INI, "ini", NULL, NULL},
    {LANG_JSON, "json", NULL, NULL},
    {LANG_JAVA, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_JAVASCRIPT, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_JULIA, "julia", "abstract break case catch const continue do else elseif end export finally for function global if import let local macro module quote return struct try type using while", NULL},
    {LANG_KOTLIN, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_LESS, "css", "color background font margin padding border width height display position top left right bottom float clear text-align vertical-align line-height font-size font-family font-weight overflow visibility z-index opacity transform transition animation flex grid justify-content align-items", NULL},
    {LANG_LUA, "lua", "and break do else elseif end false for function goto if in local nil not or repeat return then true until while", NULL},
    {LANG_MATLAB, "matlab", "break case catch classdef continue else elseif end for function global if otherwise parfor persistent return spmd switch try while", NULL},
    {LANG_MAKEFILE, "makefile", NULL, NULL},
    {LANG_MARKDOWN, "markdown", NULL, NULL},
    {LANG_MESON, "meson", NULL, NULL},
    {LANG_NIM, "nim", NULL, NULL},
    {LANG_OCAML, "ocaml", NULL, NULL},
    {LANG_OBJECTIVE_C, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_OBJECTIVE_CPP, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_PASCAL, "pascal", "and array as begin case class const constructor destructor div do downto else end except finally for function goto if implementation in inherited interface is mod not object of on or packed procedure program property raise record repeat set shl shr then to try type unit until uses var while with xor", NULL},
    {LANG_PERL, "perl", "if else elsif unless while until for foreach do last next redo goto return sub package use require BEGIN END my local our", NULL},
    {LANG_POWERSHELL, "powershell", "begin break catch class continue data define do dynamicparam else elseif end exit filter finally for foreach from function if in inlineScript parallel param process return switch throw trap try until where while workflow", NULL},
    {LANG_PYTHON, "python", "and as assert async await break class continue def del elif else except finally for from global if import in is lambda None not or pass raise return try while with yield True False", NULL},
    {LANG_R, "r", "if else repeat while function for in next break TRUE FALSE NULL NA Inf NaN", NULL},
    {LANG_RUBY, "ruby", "BEGIN END alias and begin break case class def defined? do else elsif end ensure false for if in module next nil not or redo rescue retry return self super then true undef unless until when while yield", NULL},
    {LANG_RUST, "rust", "as break const continue crate dyn else enum extern false fn for if impl in let loop match mod move mut pub ref return self Self static struct super trait true type unsafe use where while", NULL},
    {LANG_SCSS, "css", "color background font margin padding border width height display position top left right bottom float clear text-align vertical-align line-height font-size font-family font-weight overflow visibility z-index opacity transform transition animation flex grid justify-content align-items", NULL},
    {LANG_SQL, "sql", "select from where and or not in is null as order by group having join left right inner outer on union all distinct count sum avg min max", NULL},
    {LANG_SASS, "css", "color background font margin padding border width height display position top left right bottom float clear text-align vertical-align line-height font-size font-family font-weight overflow visibility z-index opacity transform transition animation flex grid justify-content align-items", NULL},
    {LANG_SCALA, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_SHELL, "bash", "if then else elif fi case esac for while until do done in function select time coproc", NULL},
    {LANG_STANDARD_ML, "sml", NULL, NULL},
    {LANG_SWIFT, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_TOML, "toml", NULL, NULL},
    {LANG_TSV, "csv", NULL, NULL},
    {LANG_TCL, "tcl", NULL, NULL},
    {LANG_TEX, "latex", NULL, NULL},
    {LANG_TYPESCRIPT, "cpp", "and and_eq asm auto bitand bitor bool break case catch char class compl const const_cast continue default delete do double dynamic_cast else enum explicit export extern false float for friend goto if inline int long mutable namespace new not not_eq operator or or_eq private protected public register reinterpret_cast return short signed sizeof static static_cast struct switch template this throw true try typedef typeid typename union unsigned using virtual void volatile wchar_t while xor xor_eq", "class public private protected virtual override final new delete this template typename namespace using try catch throw noexcept constexpr nullptr static_cast dynamic_cast const_cast reinterpret_cast explicit friend mutable operator"},
    {LANG_VHDL, "vhdl", "abs access after alias all and architecture array assert attribute begin block body buffer bus case component configuration constant disconnect downto else elsif end entity exit file for function generate generic group guarded if impure in inertial inout is label library linkage literal loop map mod nand new next nor not null of on open or others out package port postponed procedure process pure range record register reject rem report return rol ror select severity signal shared sla sll sra srl subtype then to transport type unaffected units until use variable wait when while with xnor xor", NULL},
    {LANG_VERILOG, "verilog", "always and assign automatic begin buf bufif0 bufif1 case casex casez cell cmos config deassign default defparam design disable edge else end endcase endconfig endfunction endgenerate endmodule endprimitive endspecify endtable endtask event for force forever fork function generate genvar highz0 highz1 if ifnone incdir include initial inout input instance join large liblist library localparam macromodule medium module nand negedge nmos nor noshowcancelled not notif0 notif1 or output parameter pmos posedge primitive pull0 pull1 pulldown pullup pulsestyle_ondetect pulsestyle_onevent rcmos real realtime reg release repeat rnmos rpmos rtran rtranif0 rtranif1 scalared showcancelled signed small specify specparam strong0 strong1 supply0 supply1 supply1 table task time tran tranif0 tranif1 tri tri0 tri1 triand trior trireg use uwire vectored wait wand weak0 weak1 while wire wor xnor xor", NULL},
    {LANG_WINDOWS_REGISTRY, "registry", "HKEY_CLASSES_ROOT HKEY_CURRENT_USER HKEY_LOCAL_MACHINE HKEY_USERS HKEY_CURRENT_CONFIG REG_SZ REG_DWORD REG_BINARY REG_MULTI_SZ REG_EXPAND_SZ REG_NONE REG_QWORD REG_DWORD_BIG_ENDIAN REG_LINK REG_RESOURCE_LIST REG_FULL_RESOURCE_DESCRIPTOR REG_RESOURCE_REQUIREMENTS_LIST REG_QWORD_LITTLE_ENDIAN DELETE READ_CONTROL WRITE_DAC WRITE_OWNER", NULL},
    {LANG_XML, "xml", NULL, NULL},
    {LANG_YAML, "yaml", NULL, NULL},
    {LANG_ZIG, "zig", NULL, NULL},
    {LANG_RESTRUCTUREDTEXT, "rest", NULL, NULL},
};

/* Comprehensive file filter string for save dialogs */
const char* g_fileFilters =
    "All Files\\0*.*\\0Text Files\\0*.txt\\0Programming Files\\0*.c;*.h;*.cpp;*.hpp;*.cc;*.cxx\\0Web Files\\0*.css;*.html;*.htm;*.json;*.js;*.mjs;*.xml\\0Scripting Files\\0*.py;*.pyw;*.pyi\\0";

/* Language name lookup functions */
const char* GetLanguageName(LanguageType language) {
    switch (language) {
        case LANG_NONE: return "Plain Text";
        case LANG_C: return "C";
        case LANG_CPP: return "C++";
        case LANG_PYTHON: return "Python";
        case LANG_JAVASCRIPT: return "JavaScript";
        case LANG_HTML: return "HTML";
        case LANG_CSS: return "CSS";
        case LANG_XML: return "XML";
        case LANG_JSON: return "JSON";
        case LANG_MARKDOWN: return "Markdown";
        case LANG_BATCH: return "Batch";
        case LANG_SQL: return "SQL";
        case LANG_ADA: return "Ada";
        case LANG_ASSEMBLY: return "Assembly";
        case LANG_BATCHFILE: return "Batchfile";
        case LANG_CS: return "C#";
        case LANG_CMAKE: return "CMake";
        case LANG_COBOL: return "COBOL";
        case LANG_CSV: return "CSV";
        case LANG_CLOJURE: return "Clojure";
        case LANG_COFFEESCRIPT: return "CoffeeScript";
        case LANG_D: return "D";
        case LANG_DART: return "Dart";
        case LANG_DIFF: return "Diff";
        case LANG_DOCKERFILE: return "Dockerfile";
        case LANG_ELIXIR: return "Elixir";
        case LANG_ERLANG: return "Erlang";
        case LANG_FS: return "F#";
        case LANG_FORTRAN: return "Fortran";
        case LANG_GO: return "Go";
        case LANG_GRAPHQL: return "GraphQL";
        case LANG_HTTP: return "HTTP";
        case LANG_HASKELL: return "Haskell";
        case LANG_INI: return "INI";
        case LANG_JAVA: return "Java";
        case LANG_JULIA: return "Julia";
        case LANG_KOTLIN: return "Kotlin";
        case LANG_LESS: return "Less";
        case LANG_LUA: return "Lua";
        case LANG_MATLAB: return "MATLAB";
        case LANG_MAKEFILE: return "Makefile";
        case LANG_MESON: return "Meson";
        case LANG_NIM: return "Nim";
        case LANG_OCAML: return "OCaml";
        case LANG_OBJECTIVE_C: return "Objective-C";
        case LANG_OBJECTIVE_CPP: return "Objective-C++";
        case LANG_PASCAL: return "Pascal";
        case LANG_PERL: return "Perl";
        case LANG_POWERSHELL: return "PowerShell";
        case LANG_R: return "R";
        case LANG_RUBY: return "Ruby";
        case LANG_RUST: return "Rust";
        case LANG_SCSS: return "SCSS";
        case LANG_SASS: return "Sass";
        case LANG_SCALA: return "Scala";
        case LANG_SHELL: return "Shell";
        case LANG_STANDARD_ML: return "Standard ML";
        case LANG_SWIFT: return "Swift";
        case LANG_TOML: return "TOML";
        case LANG_TSV: return "TSV";
        case LANG_TCL: return "Tcl";
        case LANG_TEX: return "TeX";
        case LANG_TYPESCRIPT: return "TypeScript";
        case LANG_VHDL: return "VHDL";
        case LANG_VERILOG: return "Verilog";
        case LANG_WINDOWS_REGISTRY: return "Windows Registry";
        case LANG_YAML: return "YAML";
        case LANG_ZIG: return "Zig";
        case LANG_RESTRUCTUREDTEXT: return "reStructuredText";
        default: return "Plain Text";
    }
}

const char* GetLanguageShortName(LanguageType language) {
    return GetLanguageName(language); /* Simplified */
}