/*
 * Auto-generated lexer mappings header
 * Generated by tools/generate_lexer_code.py
 * DO NOT EDIT - This file is automatically generated
 */

#ifndef LEXER_MAPPINGS_GENERATED_H
#define LEXER_MAPPINGS_GENERATED_H

#include <windows.h>

/* Supported language types - comprehensive list matching Scintilla lexers */
typedef enum {
    LANG_NONE, /* Plain text */
    LANG_C, /* C */
    LANG_CPP, /* C++ */
    LANG_PYTHON, /* Python */
    LANG_JAVASCRIPT, /* JavaScript */
    LANG_HTML, /* HTML */
    LANG_CSS, /* CSS */
    LANG_XML, /* XML */
    LANG_JSON, /* JSON */
    LANG_MARKDOWN, /* Markdown */
    LANG_BATCH, /* Batch */
    LANG_SQL, /* SQL */
    LANG_ADA, /* Ada */
    LANG_ASSEMBLY, /* Assembly */
    LANG_BATCHFILE, /* Batchfile */
    LANG_CS, /* C# */
    LANG_CMAKE, /* CMake */
    LANG_COBOL, /* COBOL */
    LANG_CSV, /* CSV */
    LANG_CLOJURE, /* Clojure */
    LANG_COFFEESCRIPT, /* CoffeeScript */
    LANG_D, /* D */
    LANG_DART, /* Dart */
    LANG_DIFF, /* Diff */
    LANG_DOCKERFILE, /* Dockerfile */
    LANG_ELIXIR, /* Elixir */
    LANG_ERLANG, /* Erlang */
    LANG_FS, /* F# */
    LANG_FORTRAN, /* Fortran */
    LANG_GO, /* Go */
    LANG_GRAPHQL, /* GraphQL */
    LANG_HTTP, /* HTTP */
    LANG_HASKELL, /* Haskell */
    LANG_INI, /* INI */
    LANG_JAVA, /* Java */
    LANG_JULIA, /* Julia */
    LANG_KOTLIN, /* Kotlin */
    LANG_LESS, /* Less */
    LANG_LUA, /* Lua */
    LANG_MATLAB, /* MATLAB */
    LANG_MAKEFILE, /* Makefile */
    LANG_MESON, /* Meson */
    LANG_NIM, /* Nim */
    LANG_OCAML, /* OCaml */
    LANG_OBJECTIVE_C, /* Objective-C */
    LANG_OBJECTIVE_CPP, /* Objective-C++ */
    LANG_PASCAL, /* Pascal */
    LANG_PERL, /* Perl */
    LANG_POWERSHELL, /* PowerShell */
    LANG_R, /* R */
    LANG_RUBY, /* Ruby */
    LANG_RUST, /* Rust */
    LANG_SCSS, /* SCSS */
    LANG_SASS, /* Sass */
    LANG_SCALA, /* Scala */
    LANG_SHELL, /* Shell */
    LANG_STANDARD_ML, /* Standard ML */
    LANG_SWIFT, /* Swift */
    LANG_TOML, /* TOML */
    LANG_TSV, /* TSV */
    LANG_TCL, /* Tcl */
    LANG_TEX, /* TeX */
    LANG_TYPESCRIPT, /* TypeScript */
    LANG_VHDL, /* VHDL */
    LANG_VERILOG, /* Verilog */
    LANG_WINDOWS_REGISTRY, /* Windows Registry */
    LANG_YAML, /* YAML */
    LANG_ZIG, /* Zig */
    LANG_RESTRUCTUREDTEXT, /* reStructuredText */
    LANG_COUNT
} LanguageType;



/* External declarations for generated data structures */
typedef struct {
    const char* extension;
    LanguageType language;
} ExtensionMapping;

typedef struct {
    LanguageType language;
    const char* lexerName;
    const char* keywords1;
    const char* keywords2;
} LexerConfig;

extern const ExtensionMapping g_extensionMappings[];
extern const LexerConfig g_lexerConfigs[];
extern const char* g_fileFilters;

/* Array size constants */
#define EXTENSION_MAPPING_COUNT 450
#define LEXER_CONFIG_COUNT 66

/* Function declarations for generated code */
const char* GetLanguageName(LanguageType language);
const char* GetLanguageShortName(LanguageType language);

#endif /* LEXER_MAPPINGS_GENERATED_H */
